<?php

declare(strict_types=1);

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

final class MetricsRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'cpu' => ['nullable'],
            'cpu.usage_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'cpu.user' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'cpu.system' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'cpu.nice' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'cpu.iowait' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'cpu.irq' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'cpu.softirq' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'cpu.steal' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'cpu.idle' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'ram' => ['nullable'],
            'memory' => ['nullable', 'array'],
            'memory.usage_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'memory.used_mib' => ['nullable', 'numeric', 'min:0'],
            'memory.free_mib' => ['nullable', 'numeric', 'min:0'],
            'memory.total_mib' => ['nullable', 'numeric', 'min:0'],
            'memory.cached_mib' => ['nullable', 'numeric', 'min:0'],
            'memory.buffers_mib' => ['nullable', 'numeric', 'min:0'],
            'memory.available_mib' => ['nullable', 'numeric', 'min:0'],
            'load' => ['nullable', 'array'],
            'load.load1' => ['nullable', 'numeric', 'min:0'],
            'load.load5' => ['nullable', 'numeric', 'min:0'],
            'load.load15' => ['nullable', 'numeric', 'min:0'],
            'uptime' => ['nullable', 'array'],
            'uptime.seconds' => ['nullable', 'integer', 'min:0'],
            'alerts' => ['nullable', 'array'],
            'alerts.normal' => ['nullable', 'integer', 'min:0'],
            'alerts.warning' => ['nullable', 'integer', 'min:0'],
            'alerts.critical' => ['nullable', 'integer', 'min:0'],
            'processes' => ['nullable', 'array'],
            'processes.running' => ['nullable', 'integer', 'min:0'],
            'processes.blocked' => ['nullable', 'integer', 'min:0'],
            'processes.total' => ['nullable', 'integer', 'min:0'],
            'disks' => ['nullable', 'array'],
            'disks.*.mount_point' => ['required_with:disks', 'string'],
            'disks.*.filesystem' => ['nullable', 'string'],
            'disks.*.used_gb' => ['nullable', 'numeric', 'min:0'],
            'disks.*.available_gb' => ['nullable', 'numeric', 'min:0'],
            'disks.*.total_gb' => ['nullable', 'numeric', 'min:0'],
            'disks.*.usage_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'disks.*.read_kbps' => ['nullable', 'numeric', 'min:0'],
            'disks.*.write_kbps' => ['nullable', 'numeric', 'min:0'],
            'disks.*.utilization_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'disks.*.inode_usage_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
            'network' => ['nullable', 'array'],
            'network.*.interface' => ['required_with:network', 'string'],
            'network.*.received_kbps' => ['nullable', 'numeric', 'min:0'],
            'network.*.sent_kbps' => ['nullable', 'numeric', 'min:0'],
            'network.*.received_bytes' => ['nullable', 'integer', 'min:0'],
            'network.*.sent_bytes' => ['nullable', 'integer', 'min:0'],
            'network.*.received_errors' => ['nullable', 'numeric', 'min:0'],
            'network.*.sent_errors' => ['nullable', 'numeric', 'min:0'],
            'network.*.received_drops' => ['nullable', 'numeric', 'min:0'],
            'network.*.sent_drops' => ['nullable', 'numeric', 'min:0'],
            'network.*.link_speed_mbps' => ['nullable', 'numeric', 'min:0'],
            'swap' => ['nullable', 'array'],
            'swap.used_mib' => ['nullable', 'numeric', 'min:0'],
            'swap.total_mib' => ['nullable', 'numeric', 'min:0'],
            'apps' => ['nullable', 'array', 'max:500'],
            'apps.*.name' => ['required_with:apps', 'string', 'max:255'],
            'apps.*.cpu_percent' => ['nullable', 'numeric', 'min:0'],
            'apps.*.memory_mib' => ['nullable', 'numeric', 'min:0'],
            'linux_health' => ['nullable', 'array'],
            'linux_health.failed_units' => ['nullable', 'array', 'max:200'],
            'linux_health.failed_units.*' => ['string', 'max:255'],
            'linux_health.reboot_required' => ['nullable', 'boolean'],
            'linux_health.pending_updates' => ['nullable', 'integer', 'min:0'],
            'linux_health.pending_security_updates' => ['nullable', 'integer', 'min:0'],
            'linux_health.checked_updates_at' => ['nullable', 'date'],
            'system_info' => ['nullable', 'array'],
            'system_info.netdata_version' => ['nullable', 'string', 'max:50'],
            'system_info.os_name' => ['nullable', 'string', 'max:100'],
            'system_info.os_version' => ['nullable', 'string', 'max:100'],
            'system_info.kernel_name' => ['nullable', 'string', 'max:100'],
            'system_info.kernel_version' => ['nullable', 'string', 'max:100'],
            'system_info.architecture' => ['nullable', 'string', 'max:50'],
            'system_info.virtualization' => ['nullable', 'string', 'max:100'],
            'system_info.container' => ['nullable', 'string', 'max:100'],
            'system_info.is_k8s_node' => ['nullable', 'boolean'],
            'netdata_cpu_queue' => ['nullable', 'array'],
            'netdata_apps_cpu' => ['nullable', 'array'],
            'netdata_apps_mem' => ['nullable', 'array'],
            'netdata_disk_util' => ['nullable', 'array'],
            'netdata_swap' => ['nullable', 'array'],
            'netdata_processes' => ['nullable', 'array'],
            'netdata_disk_inodes' => ['nullable', 'array'],
            'netdata_net_interfaces' => ['nullable', 'array'],
            'netdata_net_errors' => ['nullable', 'array'],
            'netdata_net_drops' => ['nullable', 'array'],
            'netdata_net_speed' => ['nullable', 'array'],
            'agent_version' => ['nullable', 'string', 'max:20'],
            'monitor_only' => ['nullable', 'boolean'],
            'mac_addresses' => ['nullable', 'array', 'max:32'],
            'mac_addresses.*' => ['string', 'mac_address'],
            'payload' => ['nullable', 'array'],
            'recorded_at' => ['nullable', 'date'],
            'timestamp' => ['nullable', 'date'],
        ];
    }

    /** @return array<string, string> */
    public function messages(): array
    {
        return [
            'disks.*.inode_usage_percent.numeric' => 'Inode usage must be a percentage.',
            'disks.*.inode_usage_percent.min' => 'Inode usage cannot be below 0%.',
            'disks.*.inode_usage_percent.max' => 'Inode usage cannot be above 100%.',
            'network.*.received_errors.min' => 'Network error counts cannot be negative.',
            'network.*.sent_errors.min' => 'Network error counts cannot be negative.',
            'network.*.received_drops.min' => 'Network drop counts cannot be negative.',
            'network.*.sent_drops.min' => 'Network drop counts cannot be negative.',
            'network.*.link_speed_mbps.numeric' => 'Link speed must be a number of Mbps.',
            'network.*.link_speed_mbps.min' => 'Link speed cannot be negative.',
            'swap.array' => 'Swap must be an object with used_mib and total_mib.',
            'swap.used_mib.numeric' => 'Swap used must be a number of MiB.',
            'swap.used_mib.min' => 'Swap used cannot be negative.',
            'swap.total_mib.numeric' => 'Swap total must be a number of MiB.',
            'swap.total_mib.min' => 'Swap total cannot be negative.',
            'apps.array' => 'Apps must be a list of processes.',
            'apps.max' => 'Send at most :max apps per report.',
            'apps.*.name.required_with' => 'Every app needs a name.',
            'apps.*.name.max' => 'App names may not be longer than :max characters.',
            'apps.*.cpu_percent.min' => 'App CPU usage cannot be negative.',
            'apps.*.memory_mib.min' => 'App memory cannot be negative.',
            'linux_health.array' => 'Linux health must be an object.',
            'linux_health.failed_units.array' => 'Failed units must be a list of unit names.',
            'linux_health.failed_units.max' => 'Send at most :max failed units.',
            'linux_health.failed_units.*.string' => 'Each failed unit must be a unit name.',
            'linux_health.failed_units.*.max' => 'Unit names may not be longer than :max characters.',
            'linux_health.reboot_required.boolean' => 'Reboot required must be true or false.',
            'linux_health.pending_updates.integer' => 'Pending updates must be a whole number.',
            'linux_health.pending_updates.min' => 'Pending updates cannot be negative.',
            'linux_health.pending_security_updates.integer' => 'Pending security updates must be a whole number.',
            'linux_health.pending_security_updates.min' => 'Pending security updates cannot be negative.',
            'linux_health.checked_updates_at.date' => 'The update check time must be an RFC 3339 date.',
            'netdata_processes.array' => 'Processes must be a raw Netdata response.',
            'netdata_disk_inodes.array' => 'Disk inodes must be a raw Netdata response.',
        ];
    }
}
